[keyboard]
bindings = [
		{ chars = "\u0001", key = "A", mods = "Command" }, # Ctrl + A
		{ chars = "\u0002", key = "B", mods = "Command" }, # Ctrl + B
		{ chars = "\u0003", key = "C", mods = "Command" }, # Ctrl + C
		{ chars = "\u0004", key = "D", mods = "Command" }, # Ctrl + D
	  	{ chars = "\u0005", key = "E", mods = "Command" }, # Ctrl + E
	  	{ chars = "\u0006", key = "F", mods = "Command" }, # Ctrl + F
	  	{ chars = "\u0007", key = "G", mods = "Command" }, # Ctrl + G
	  	{ chars = "\u0008", key = "H", mods = "Command" }, # Ctrl + H
	  	{ chars = "\u0009", key = "I", mods = "Command" }, # Ctrl + I
	  	{ chars = "\u000A", key = "J", mods = "Command" }, # Ctrl + J
	  	{ chars = "\u000B", key = "K", mods = "Command" }, # Ctrl + K
	  	{ chars = "\u000C", key = "L", mods = "Command" }, # Ctrl + L
	  	{ chars = "\u000D", key = "M", mods = "Command" }, # Ctrl + M
	  	{ chars = "\u000E", key = "N", mods = "Command" }, # Ctrl + N
	  	{ chars = "\u000F", key = "O", mods = "Command" }, # Ctrl + O
	  	{ chars = "\u0010", key = "P", mods = "Command" }, # Ctrl + P
	  	{ chars = "\u0011", key = "Q", mods = "Command" }, # Ctrl + Q
	  	{ chars = "\u0012", key = "R", mods = "Command" }, # Ctrl + R
	  	{ chars = "\u0013", key = "S", mods = "Command" }, # Ctrl + S
	  	{ chars = "\u0014", key = "T", mods = "Command" }, # Ctrl + T
	  	{ chars = "\u0015", key = "U", mods = "Command" }, # Ctrl + U
	  	{ chars = "\u0016", key = "V", mods = "Command" }, # Ctrl + V
	  	{ chars = "\u0017", key = "W", mods = "Command" }, # Ctrl + W
	  	{ chars = "\u0018", key = "X", mods = "Command" }, # Ctrl + X
	  	{ chars = "\u0019", key = "Y", mods = "Command" }, # Ctrl + Y
	  	{ chars = "\u001A", key = "Z", mods = "Command" }, # Ctrl + Z
	  	{ chars = "\u001B", key = "[", mods = "Command" }, # Ctrl + [
	  	{ chars = "\u001C", key = "\\", mods = "Command" },# Ctrl + \
	  	{ chars = "\u001D", key = "]", mods = "Command" }, # Ctrl + ]
	  	{ chars = "\u001E", key = "^", mods = "Command" }, # Ctrl + ^
	  	{ chars = "\u001F", key = "_", mods = "Command" }, # Ctrl + _
	  	{ action = "CreateNewWindow", 	key = "N", 		mods = "Control" },
	  	{ action = "Paste", 			key = "Space", 	mods = "Command | Shift" },
	  	{ action = "None", 				key = "=", 		mods = "Command" },
	  	{ chars = "\u001BF", 			key = "Right", 	mods = "Control" },
	  	{ chars = "\u001BB", 			key = "Left", 	mods = "Control" },
]
