# --- General ---
set -g default-terminal "screen-256color"
set -g history-limit 10000
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set-option -g automatic-rename off

# --- Editor ---
set-option -g editor "nvim"

# unbind C-a
# set -g prefix C-w
# bind C-w send-prefix


# # --- Status line ---
# set -g status-interval 5
# set -g status-justify centre
# set -g status-left-length 40
# set -g status-right-length 80
# set -g status-style "bg=colour235,fg=colour136"
#
# set -g status-left "#[fg=colour81]#S #[fg=colour240]|"
# set -g status-right "#[fg=colour240]%Y-%m-%d %H:%M"
# # Hide status line 
set -g status off

setw -g window-status-current-style "bg=colour240,fg=colour81"
setw -g window-status-style "bg=colour235,fg=colour244"

# --- Copy/Selection ---
set -g mode-style "bg=colour236,fg=colour81"
set -g message-style "bg=colour235,fg=colour81"
set -g message-command-style "bg=colour235,fg=colour81"

# --- Keybinds ---
# Use vim keys in copy mode
setw -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

# Split panes
bind "\\" split-window -h
bind "-" split-window -v
unbind '"'
unbind %

# Easier reload
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"

unbind h; bind h select-pane -L
unbind j; bind j select-pane -D
unbind k; bind k select-pane -U
unbind l; bind l select-pane -R

# Create a shell variable to check if inside Neovim
is_nvim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+/)?g?(view|n?vim?x?)(diff)?$'"

# Conditional bindings for pane navigation
# bind-key h if-shell "$is_nvim" 'send-keys C-w h' 'select-pane -L'
# bind-key j if-shell "$is_nvim" 'send-keys C-w j' 'select-pane -D'
# bind-key k if-shell "$is_nvim" 'send-keys C-w k' 'select-pane -U'
# bind-key l if-shell "$is_nvim" 'send-keys C-w l' 'select-pane -R'

# Shift-movement for pane resizing in tmux, sends to neovim if active
# bind-key H if-shell "$is_nvim" 'send-keys C-w H' 'resize-pane -L 5'
# bind-key J if-shell "$is_nvim" 'send-keys C-w J' 'resize-pane -D 5'
# bind-key K if-shell "$is_nvim" 'send-keys C-w K' 'resize-pane -U 5'
# bind-key L if-shell "$is_nvim" 'send-keys C-w L' 'resize-pane -R 5'
# Fix colors in nvim inside tmux ---
set-option -sa terminal-overrides ',xterm-256color:Tc'

